name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Leiningen
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        lein: latest

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test